version: "3.8"
services:
  app:
    container_name: get-it-angular
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    command: sh -c "npm start"
    ports:
      - 80:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - web
    restart: always

  api:
    container_name: get-it-node-server
    image: sample-express-app
    build: ./nodejs-server
    volumes:
      - ./nodejs-server:/usr/src/app
    ports:
      - "3307:3307"
    networks:
      - web
    restart: always

  db:
    container_name: get-it-database
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db'
      MYSQL_ROOT_PASSWORD: 'db'
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - web

  phpmyadmin:
    container_name: get-it-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
      - web

volumes:
  database:
  node_modules:

networks:
  web:
